export interface SystemEmoji {
	name: string;
	char: string;
}

export interface SystemEmojiGroup {
	category: string;
	items: SystemEmoji[];
}

export const SYSTEM_EMOJI_GROUPS: SystemEmojiGroup[] = [
	{ category: 'faces', items: [
		{ name: 'grinning', char: '😀' },
		{ name: 'smiley', char: '😃' },
		{ name: 'smile', char: '😄' },
		{ name: 'grin', char: '😁' },
		{ name: 'laughing', char: '😆' },
		{ name: 'sweat_smile', char: '😅' },
		{ name: 'rofl', char: '🤣' },
		{ name: 'joy', char: '😂' },
		{ name: 'slightly_smiling_face', char: '🙂' },
		{ name: 'upside_down_face', char: '🙃' },
		{ name: 'wink', char: '😉' },
		{ name: 'blush', char: '😊' },
		{ name: 'innocent', char: '😇' },
		{ name: 'smiling_face_with_three_hearts', char: '🥰' },
		{ name: 'heart_eyes', char: '😍' },
		{ name: 'star_struck', char: '🤩' },
		{ name: 'kissing_heart', char: '😘' },
		{ name: 'kissing', char: '😗' },
		{ name: 'relaxed', char: '☺️' },
		{ name: 'kissing_closed_eyes', char: '😚' },
		{ name: 'kissing_smiling_eyes', char: '😙' },
		{ name: 'yum', char: '😋' },
		{ name: 'stuck_out_tongue', char: '😛' },
		{ name: 'stuck_out_tongue_winking_eye', char: '😜' },
		{ name: 'zany_face', char: '🤪' },
		{ name: 'stuck_out_tongue_closed_eyes', char: '😝' },
		{ name: 'money_mouth_face', char: '🤑' },
		{ name: 'hugs', char: '🤗' },
		{ name: 'hand_over_mouth', char: '🤭' },
		{ name: 'shushing_face', char: '🤫' },
		{ name: 'thinking', char: '🤔' },
		{ name: 'zipper_mouth_face', char: '🤐' },
		{ name: 'raised_eyebrow', char: '🤨' },
		{ name: 'neutral_face', char: '😐' },
		{ name: 'expressionless', char: '😑' },
		{ name: 'no_mouth', char: '😶' },
		{ name: 'smirk', char: '😏' },
		{ name: 'unamused', char: '😒' },
		{ name: 'roll_eyes', char: '🙄' },
		{ name: 'grimacing', char: '😬' },
		{ name: 'lying_face', char: '🤥' },
		{ name: 'relieved', char: '😌' },
		{ name: 'pensive', char: '😔' },
		{ name: 'sleepy', char: '😪' },
		{ name: 'drooling_face', char: '🤤' },
		{ name: 'sleeping', char: '😴' },
		{ name: 'mask', char: '😷' },
		{ name: 'face_with_thermometer', char: '🤒' },
		{ name: 'face_with_head_bandage', char: '🤕' },
		{ name: 'nauseated_face', char: '🤢' },
		{ name: 'vomiting_face', char: '🤮' },
		{ name: 'sneezing_face', char: '🤧' },
		{ name: 'cold_face', char: '🥶' },
		{ name: 'hot_face', char: '🥵' },
		{ name: 'dizzy_face', char: '😵' },
		{ name: 'exploding_head', char: '🤯' },
		{ name: 'cowboy_hat_face', char: '🤠' },
		{ name: 'partying_face', char: '🥳' },
		{ name: 'sunglasses', char: '😎' },
		{ name: 'nerd_face', char: '🤓' },
		{ name: 'monocle_face', char: '🧐' },
		{ name: 'confused', char: '😕' },
		{ name: 'worried', char: '😟' },
		{ name: 'slightly_frowning_face', char: '🙁' },
		{ name: 'frowning_face', char: '☹️' },
		{ name: 'open_mouth', char: '😮' },
		{ name: 'hushed', char: '😯' },
		{ name: 'astonished', char: '😲' },
		{ name: 'flushed', char: '😳' },
		{ name: 'pleading_face', char: '🥺' },
		{ name: 'frowning', char: '😦' },
		{ name: 'anguished', char: '😧' },
		{ name: 'fearful', char: '😨' },
		{ name: 'cold_sweat', char: '😰' },
		{ name: 'disappointed_relieved', char: '😥' },
		{ name: 'cry', char: '😢' },
		{ name: 'sob', char: '😭' },
		{ name: 'scream', char: '😱' },
		{ name: 'confounded', char: '😖' },
		{ name: 'persevere', char: '😣' },
		{ name: 'disappointed', char: '😞' },
		{ name: 'sweat', char: '😓' },
		{ name: 'weary', char: '😩' },
		{ name: 'tired_face', char: '😫' },
		{ name: 'triumph', char: '😤' },
		{ name: 'rage', char: '😡' },
		{ name: 'angry', char: '😠' },
		{ name: 'smiling_imp', char: '😈' },
		{ name: 'imp', char: '👿' },
		{ name: 'skull', char: '💀' },
		{ name: 'ghost', char: '👻' },
		{ name: 'alien', char: '👽' },
		{ name: 'robot', char: '🤖' },
		{ name: 'eyes', char: '👀' },
	] },
	{ category: 'gestures', items: [
		{ name: 'clap', char: '👏' },
		{ name: 'raised_hands', char: '🙌' },
		{ name: 'open_hands', char: '👐' },
		{ name: 'handshake', char: '🤝' },
		{ name: 'thumbsup', char: '👍' },
		{ name: 'thumbsdown', char: '👎' },
		{ name: 'fist', char: '✊' },
		{ name: 'punch', char: '👊' },
		{ name: 'vulcan_salute', char: '🖖' },
		{ name: 'ok_hand', char: '👌' },
		{ name: 'pinching_hand', char: '🤏' },
		{ name: 'victory', char: '✌️' },
		{ name: 'crossed_fingers', char: '🤞' },
		{ name: 'love_you_gesture', char: '🤟' },
		{ name: 'metal', char: '🤘' },
		{ name: 'call_me_hand', char: '🤙' },
		{ name: 'point_left', char: '👈' },
		{ name: 'point_right', char: '👉' },
		{ name: 'point_up_2', char: '👆' },
		{ name: 'point_down', char: '👇' },
		{ name: 'point_up', char: '☝️' },
		{ name: 'wave', char: '👋' },
		{ name: 'muscle', char: '💪' },
		{ name: 'pray', char: '🙏' },
	] },
	{ category: 'hearts', items: [
		{ name: 'heart', char: '❤️' },
		{ name: 'orange_heart', char: '🧡' },
		{ name: 'yellow_heart', char: '💛' },
		{ name: 'green_heart', char: '💚' },
		{ name: 'blue_heart', char: '💙' },
		{ name: 'purple_heart', char: '💜' },
		{ name: 'black_heart', char: '🖤' },
		{ name: 'broken_heart', char: '💔' },
		{ name: 'two_hearts', char: '💕' },
		{ name: 'sparkling_heart', char: '💖' },
		{ name: 'heartpulse', char: '💗' },
		{ name: 'cupid', char: '💘' },
		{ name: 'gift_heart', char: '💝' },
		{ name: 'heartbeat', char: '💓' },
		{ name: 'revolving_hearts', char: '💞' },
		{ name: 'heart_exclamation', char: '❣️' },
		{ name: 'kiss', char: '💋' },
	] },
	{ category: 'symbols', items: [
		{ name: '100', char: '💯' },
		{ name: 'anger', char: '💢' },
		{ name: 'boom', char: '💥' },
		{ name: 'dizzy', char: '💫' },
		{ name: 'sweat_drops', char: '💦' },
		{ name: 'dash', char: '💨' },
		{ name: 'hole', char: '🕳️' },
		{ name: 'bomb', char: '💣' },
		{ name: 'speech_balloon', char: '💬' },
	] },
	{ category: 'nature', items: [
		{ name: 'fire', char: '🔥' },
		{ name: 'sparkles', char: '✨' },
		{ name: 'star', char: '⭐' },
		{ name: 'star2', char: '🌟' },
		{ name: 'rainbow', char: '🌈' },
		{ name: 'sunny', char: '☀️' },
		{ name: 'full_moon', char: '🌕' },
		{ name: 'crescent_moon', char: '🌙' },
		{ name: 'zap', char: '⚡' },
		{ name: 'snowflake', char: '❄️' },
		{ name: 'umbrella', char: '☔' },
		{ name: 'cloud', char: '☁️' },
		{ name: 'ocean', char: '🌊' },
		{ name: 'droplet', char: '💧' },
	] },
	{ category: 'animals', items: [
		{ name: 'cat', char: '🐱' },
		{ name: 'dog', char: '🐶' },
		{ name: 'lion', char: '🦁' },
		{ name: 'tiger', char: '🐯' },
		{ name: 'panda_face', char: '🐼' },
		{ name: 'monkey', char: '🐵' },
		{ name: 'koala', char: '🐨' },
		{ name: 'penguin', char: '🐧' },
		{ name: 'rabbit', char: '🐰' },
		{ name: 'frog', char: '🐸' },
		{ name: 'unicorn', char: '🦄' },
		{ name: 'bee', char: '🐝' },
		{ name: 'butterfly', char: '🦋' },
		{ name: 'turtle', char: '🐢' },
		{ name: 'snail', char: '🐌' },
		{ name: 'octopus', char: '🐙' },
		{ name: 'fish', char: '🐟' },
		{ name: 'whale', char: '🐳' },
		{ name: 'dolphin', char: '🐬' },
		{ name: 'chicken', char: '🐔' },
		{ name: 'owl', char: '🦉' },
		{ name: 'fox', char: '🦊' },
	] },
	{ category: 'food', items: [
		{ name: 'apple', char: '🍎' },
		{ name: 'banana', char: '🍌' },
		{ name: 'watermelon', char: '🍉' },
		{ name: 'grapes', char: '🍇' },
		{ name: 'strawberry', char: '🍓' },
		{ name: 'peach', char: '🍑' },
		{ name: 'cherry', char: '🍒' },
		{ name: 'lemon', char: '🍋' },
		{ name: 'pizza', char: '🍕' },
		{ name: 'hamburger', char: '🍔' },
		{ name: 'fries', char: '🍟' },
		{ name: 'hotdog', char: '🌭' },
		{ name: 'taco', char: '🌮' },
		{ name: 'burrito', char: '🌯' },
		{ name: 'popcorn', char: '🍿' },
		{ name: 'doughnut', char: '🍩' },
		{ name: 'cookie', char: '🍪' },
		{ name: 'cake', char: '🎂' },
		{ name: 'icecream', char: '🍦' },
		{ name: 'chocolate_bar', char: '🍫' },
		{ name: 'candy', char: '🍬' },
		{ name: 'lollipop', char: '🍭' },
		{ name: 'beer', char: '🍺' },
		{ name: 'cocktail', char: '🍸' },
		{ name: 'wine_glass', char: '🍷' },
		{ name: 'coffee', char: '☕' },
		{ name: 'tea', char: '🍵' },
		{ name: 'milk_glass', char: '🥛' },
	] },
	{ category: 'travel', items: [
		{ name: 'rocket', char: '🚀' },
		{ name: 'airplane', char: '✈️' },
		{ name: 'car', char: '🚗' },
		{ name: 'bus', char: '🚌' },
		{ name: 'train', char: '🚆' },
		{ name: 'bike', char: '🚲' },
		{ name: 'sailboat', char: '⛵' },
	] },
	{ category: 'party', items: [
		{ name: 'tada', char: '🎊' },
		{ name: 'balloon', char: '🎈' },
		{ name: 'gift', char: '🎁' },
		{ name: 'birthday', char: '🎉' },
	] },
	{ category: 'objects', items: [
		{ name: 'trophy', char: '🏆' },
		{ name: 'medal', char: '🏅' },
		{ name: 'video_game', char: '🎮' },
		{ name: 'game_die', char: '🎲' },
		{ name: 'musical_note', char: '🎵' },
		{ name: 'notes', char: '🎶' },
		{ name: 'headphones', char: '🎧' },
		{ name: 'guitar', char: '🎸' },
		{ name: 'clapper', char: '🎬' },
		{ name: 'money_bag', char: '💰' },
		{ name: 'dollar', char: '💵' },
		{ name: 'credit_card', char: '💳' },
		{ name: 'phone', char: '📱' },
		{ name: 'computer', char: '💻' },
		{ name: 'camera', char: '📷' },
		{ name: 'movie_camera', char: '🎥' },
		{ name: 'mag', char: '🔍' },
		{ name: 'bulb', char: '💡' },
		{ name: 'hourglass', char: '⏳' },
		{ name: 'bell', char: '🔔' },
		{ name: 'checkered_flag', char: '🏁' },
	] },
];


export async function renderSystemEmojiPng(char: string): Promise<ArrayBuffer> {
	const size = 256;
	const canvas = createEl('canvas');
	canvas.width = size;
	canvas.height = size;
	try {
		const ctx = canvas.getContext('2d');
		if (!ctx) throw new Error('Canvas is not available.');
		ctx.clearRect(0, 0, size, size);
		ctx.font = `${Math.floor(size * 0.78)}px "Segoe UI Emoji", "Apple Color Emoji", "Noto Color Emoji", sans-serif`;
		ctx.textAlign = 'center';
		ctx.textBaseline = 'middle';
		ctx.fillText(char, size / 2, size / 2 + size * 0.04);
		const blob =
			(await new Promise<Blob | null>((resolve) =>
				canvas.toBlob(resolve, 'image/png'),
			)) ?? dataUrlToBlob(canvas.toDataURL('image/png'));
		if (!blob) throw new Error('Could not render the emoji image.');
		return blob.arrayBuffer();
	} finally {
		canvas.remove();
	}
}

function dataUrlToBlob(dataUrl: string): Blob | null {
	const comma = dataUrl.indexOf(',');
	if (comma === -1) return null;
	const binary = atob(dataUrl.slice(comma + 1));
	const bytes = new Uint8Array(binary.length);
	for (let i = 0; i < binary.length; i++) {
		bytes[i] = binary.charCodeAt(i);
	}
	return new Blob([bytes], { type: 'image/png' });
}